spring.application.name=ms-jugadores
server.port = 8084

spring.datasource.url=jdbc:mysql://localhost:3306/ms_jugadores?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=clave_super_secreta_12345678901234567890