spring.application.name=ms-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-equipos
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-equipos
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/equipos/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-estadisticas
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-estadisticas
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/estadisticas/**

spring.cloud.gateway.server.webmvc.routes[3].id=ms-juegos
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-juegos
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/juegos/**

spring.cloud.gateway.server.webmvc.routes[4].id=ms-jugadores
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ms-jugadores
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/jugadores/**

spring.cloud.gateway.server.webmvc.routes[5].id=ms-partidas
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ms-partidas
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/partidas/**

spring.cloud.gateway.server.webmvc.routes[6].id=ms-torneos
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ms-torneos
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/torneos/**

spring.cloud.gateway.server.webmvc.routes[7].id=ms-notificaciones
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://ms-notificaciones
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/notificaciones/**

spring.cloud.gateway.server.webmvc.routes[8].id=ms-patrocinadores
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ms-patrocinadores
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/patrocinadores/**

spring.cloud.gateway.server.webmvc.routes[9].id=ms-rankings
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ms-rankings
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/v1/rankings/**

spring.cloud.gateway.server.webmvc.routes[10].id=ms-transferencias
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://ms-transferencias
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/v1/transferencias/**

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true